name: Telegram bot ⚡
on:
  push:
    branches:
      - master
    workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  Learning-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: python bot.py
        
